apiVersion: v1
kind: ConfigMap
metadata:
  name: marketplace-config
data:
  postgres-db: marketplace_db
  mongo-db: marketplace_db
  postgres-host: postgres
  postgres-port: "5433"
  mongo-host: mongo
  mongo-port: "27018"
  redis-host: redis
  redis-port: "6379"
  elasticsearch-host: elasticsearch
  elasticsearch-port: "9200"
